version: 1.2.0.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget.exe restore PSI_Interface.sln
build:
  project: PSI_Interface.sln
  verbosity: minimal
test: off
artifacts:
- path: PSI_Interface\bin\Release\PSI_Interface*.nupkg
notifications:
- provider: Email
  to:
  - bryson.gibbons@pnnl.gov
  on_build_failure: true
