// DO NOT EDIT THIS FILE!
// This file is autogenerated from the internet-sourced OBO files.
// Any edits made will be lost when it is recreated.

// ReSharper disable InconsistentNaming

namespace PSI_Interface.CV
{
    public static partial class CV
    {
        /// <summary>Populate the list of included Controlled Vocabularies, with descriptive information</summary>
        public static void PopulateCVInfoList()
        {
            CVInfoList.Add(new CVInfo("MS", "Proteomics Standards Initiative Mass Spectrometry Ontology", "https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.obo", "4.1.108"));
            CVInfoList.Add(new CVInfo("NCIT", "Proteomics Standards Initiative Mass Spectrometry Ontology", "https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.obo", "4.1.108"));
            CVInfoList.Add(new CVInfo("PEFF", "Proteomics Standards Initiative Mass Spectrometry Ontology", "https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.obo", "4.1.108"));
            CVInfoList.Add(new CVInfo("UO", "Proteomics Standards Initiative Mass Spectrometry Ontology", "https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.obo", "4.1.108"));
            CVInfoList.Add(new CVInfo("UNIMOD", "UNIMOD", "http://www.unimod.org/obo/unimod.obo", "20:10:2022 14:06"));
        }

        /// <summary>Enum listing all relationships between CV terms used in the included CVs</summary>
        public enum RelationsOtherTypes : int
        {
            /// <summary>Unknown term relationship</summary>
            Unknown,

            /// <summary>Description not provided</summary>
            has_regexp,

            /// <summary>Description not provided</summary>
            has_units,

            /// <summary>Description not provided</summary>
            has_order,

            /// <summary>Description not provided</summary>
            has_domain,

            /// <summary>"'Entity A' has value type 'Entity B', such as xsd:float."</summary>
            has_value_type,

            /// <summary>"The term is encoded in the structure of the named file format rather than as an explicit parameter, and should not be used as one in that format."</summary>
            has_structured_representation_in_format,

            /// <summary>Description not provided</summary>
            has_metric_category,

            /// <summary>Description not provided</summary>
            has_value_concept,

            /// <summary>Description not provided</summary>
            has_column,

            /// <summary>Description not provided</summary>
            has_optional_column,

        }
    }
}
